### ISSUE TITLE
FirtzBox firmware 7.25 breaks script

### ISSUE THREAD

**Issue by mpsdskd** [Schmidsfeld/TelegrafFritzBox#9]
The latest firmware update seems to brake the script or the readout of its output with telegraf:
- Telegraf error message: `Mar 13 09:41:36 pi telegraf[382407]: 2021-03-13T09:41:36Z E! [inputs.exec] Error in plugin: metric parse error: expected tag at 1:10: "FritzBox,,source=general ,WANAccessType=\"DSL\",Firmware=\"7.25\""`
- Script output:
```
python3 /usr/local/bin/telegrafFritzBox.py -i fritz.box -p _nope_
FritzBox,,source=general ,WANAccessType="DSL",Firmware="7.25"
FritzBox,,source=status 
FritzBox,,source=wan ,Layer1DownstreamMaxBitRate=113992000i,Layer1UpstreamMaxBitRate=39822000i,ByteReceiveRate=461432i,ByteSendRate=12588i,PacketReceiveRate=0i,PacketSendRate=0i,TotalBytesReceived64=4180191888,TotalBytesSent64=2551277100
FritzBox,,source=dsl 
FritzBox,,source=network ,HostNumberOfEntries=64i,HostsKnown=64i,HostsKnownLAN=1i,HostsKnownWLAN=18i,HostsActive=20i,HostsActiveLAN=1i,HostsActiveWLAN=18i
FritzBox,,source=lan 
FritzBox,,source=wlan_2.4GHz 
FritzBox,,source=wlan_5GHz 
FritzBox,,source=wlan_Guest 
```

I already updated fritzconnection and tried removing the double comma (`Error in plugin: metric parse error: expected tag at 1:60: "FritzBox,source=general,WANAccessType=\"DSL\",Firmware=\"7.25\""`). No I cannot really go on as I do not knowwhat the output _should_ look like for it to work.

**Comment by FerFemNemBem** [comment]
Hi,

the new FB-Firmware needs a username beside the password.
So please try:
python3 /usr/local/bin/telegrafFritzBox.py -i fritz.box -p secret -u me
But I wondering why you in general get an output without setting a username.

This way works for me (FB 7950 FW 7.25) without any problems.

Cheers,
Jan


Am 13.03.2021 um 10:46 schrieb mpsdskd:

**Comment by mpsdskd** [comment]
Thanks a lot, that did it! :+1: 

At least I have the excuse that I DID get some data, so I did not assume any authentication problems ;)

It always used to work for me that way with the password printed on the back of the FritzBox - until the upgrade yesterday.

**Comment by stillbeben** [comment]
Using a username + pass doesn't do the trick for me (7590):

```
$ python3 /opt/telegraffritzbox/telegrafFritzBox.py -u rico -p "super-secret"
FritzBox,,source=general ,WANAccessType="DSL",Firmware="7.25"
...
```

Login to the webinterface with this user works fine.

**Comment by mpsdskd** [comment]
What works for me is:
```python3 /wherever-your-script-is/telegrafFritzBox.py -i fritz.box -p password -u user```
with the password that's written on the label on the FirtzBox's underside and the user from 
FritzBox UI --> System --> FRITZ!Box-Benutzer (Users) - chose the automatically created user.
